#   updated standardization to rates syntax

#---------------------------------------------------------#
#   edu 2026 proj  4/9/2026
#'  Ted, Will, Tess, Ayesha
#'  Ted:  revised to begin with full raw dataset
#'  all_subs_raw_2026.csv
#---------------------------------------------------------#

#          _.-^~~^^^`~-,_,,~''''''```~,''``~'``~,
#  ______,'  -o  :.  _    .          ;     ,'`,  `.
# (      -\.._,.;;'._ ,(   }        _`_-_,,    `, `,
#  ``~~~~~~'   ((/'((((____/~~~~~~'(,(,___>      `~'
#---------------------------------------------------------#                     


#  need to install packages for your first use of the package
#  thereafter you need to run library at the start of each
#  new sesssion.
         
# Load packages, data

library(data.table)
library(tidyverse)


#   specifics of this syntax are written for dataset produced using
#   2026 version of thread_dataset_inator version 1 but 2,3 should work
#   if you have made new terms and phrase variables obviously you need
#   to update the lists below

df <- fread("all_subs_raw_2026.csv") |>
  janitor::clean_names()

names(df)     

df <- df %>% 
  mutate(
    # Create com_count: if t.comments is less than 501, keep its value; 
    # otherwise, set it to the maximum cap of 500.
    com_count = if_else(
      t_comments < 501,
      t_comments,
      500
    )
  )

summary(df$com_count)

#    results:
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#    9.0    41.0    90.0   154.9   214.0   500.0 

# 1. Define a list of additional numeric variables to exclude from standardization.
#    'com_count' must be included here since it is the denominator.
#    Replace 'variable_name_1', 'variable_name_2', etc., with the actual names 
#    of the numeric variables you want to exclude.



vars_to_exclude <- c("com_count", 
                     "url",
                     "author",
                     "date",
                     "timestamp",
                     "score",
                     "upvotes",
                     "downvotes",
                     "golds",
                     "comment",
                     "comment_id",
                     "t_author",
                     "t_date",
                     "t_title",
                     "t_subreddit",
                     "t_upvotes",
                     "t_up_ratio",
                     "t_total_awards",
                     "t_golds",
                     "t_cross_posts",
                     "t_comments",
                     "topic",
                     "word_count")





# 2. Perform standardization (rate calculation)
df <- df %>% 
  mutate(
    across(
      where(is.numeric) & !all_of(vars_to_exclude), 
      ~ (. / com_count) * 100,                            
      .names = "{.col}_rt"              
    ),
    # Coerce all newly created rate columns to numeric.
    # across() with ends_with("_rt") targets only the columns added in the
    # step above, so no other columns are affected.
    across(
      ends_with("_rt"),
      as.numeric
    )
  )

hist(df$ai_rt)
table(df$ai_rt)

summary(df$ai_rt)

vars_to_drop<- c("makevar",
                 "tik_tok",
                 "instagram",
                 "the_gram",
                 "social_media",
                 "snap_chat",
                 "you_tube",
                 "youtube",
                 "twitter",
                 "xitter",
                 "facebook",
                 "threads",
                 "twitch",
                 "reddit",
                 "whatsapp",
                 "texting",
                 "groupme",
                 "wikipedia",
                 "email",
                 "phone",
                 "screen_addict",
                 "phone_addict",
                 "digital_addict",
                 "ipad_kid",
                 "ipad_baby",
                 "ipad_babies",
                 "screenager",
                 "device_addict",
                 "screen_obsession",
                 "screen_time",
                 "chrome_book",
                 "chromebook",
                 "enjoy_the_process",
                 "passion_for_teach",
                 "intrinsic_motiv",
                 "extrinsic_motiv",
                 "take_ownership",
                 "inquisitive",
                 "curiosity",
                 "passion_for_learning",
                 "walk_the_halls",
                 "skip_class",
                 "plagiarism",
                 "cheat",
                 "plagiarize",
                 "turnitin",
                 "lock_down_browser",
                 "low_attendance",
                 "is_class_mandatory",
                 "skipping_class",
                 "is_attendance",
                 "chat_gpt_to_write",
                 "ai_to_write",
                 "artificial_intelligence",
                 "robot",
                 "chat_gpt",
                 "llm",
                 "claude",
                 "gemini",
                 "chat_gpt_2",
                 "grok",
                 "anthropic",
                 "depress",
                 "sad",
                 "stress",
                 "anxious",
                 "anxiety",
                 "mental_health",
                 "generation_z",
                 "no_motivation",
                 "not_motivated",
                 "too_exhausted",
                 "i_am_done",
                 "i_cant_anymore",
                 "burned_out",
                 "burn_out",
                 "i_quit",
                 "considering_leaving_this_profession",
                 "love_teaching_but",
                 "why_am_i_even_here",
                 "like_i_cant_win",
                 "wasting_my_time",
                 "why_do_i_even_try",
                 "i_really_think",
                 "i_really_believe",
                 "i_believe",
                 "i_do_believe",
                 "i_feel",
                 "i_know",
                 "i_just_think",
                 "i_think",
                 "i_thought",
                 "i_agree",
                 "appreciate",
                 "grateful",
                 "thank_you",
                 "thanks",
                 "they_believe",
                 "they_claim",
                 "they_say",
                 "they_think",
                 "they_want",
                 "they_dont_believe",
                 "they_dont_think",
                 "deleted",
                 "gen_z",
                 "zoomer",
                 "gen_alpha",
                 "nt_talk",
                 "not_talk",
                 "nt_answer",
                 "not_answer",
                 "nt_respond",
                 "not_respond",
                 "nt_say",
                 "not_say",
                 "nt_read",
                 "not_read",
                 "nt_multiply",
                 "not_multiply",
                 "nt_divide",
                 "not_divide",
                 "nt_draw",
                 "not_draw",
                 "nt_do",
                 "not_do",
                 "nt_know",
                 "not_know",
                 "nt_understand",
                 "not_understand",
                 "nt_digest",
                 "not_digest",
                 "nt_name",
                 "not_name",
                 "struggle_to",
                 "struggle_with",
                 "lack_profic",
                 "lack_basic",
                 "lack_fundament",
                 "in_diapers",
                 "potty_train",
                 "never_develop",
                 "stick_figure",
                 "who_couldnt_properly",
                 "nt_even_add",
                 "no_idea_how_to",
                 "at_grade_level",
                 "below_grade_level",
                 "nt_care_about_school",
                 "parents_dont_care",
                 "parents_dont_help",
                 "parents_have_no",
                 "parents_arent",
                 "parents_do_not",
                 "want_to_parent",
                 "wants_to_parent",
                 "nt_listen",
                 "not_listen",
                 "nt_pay_attention",
                 "not_pay_attention",
                 "nt_focus",
                 "not_focus",
                 "nt_engage",
                 "not_engage",
                 "no_engage",
                 "tuned_out",
                 "checked_out",
                 "not_interested",
                 "no_interest",
                 "zone_out",
                 "bored_in_class",
                 "nt_motiva",
                 "not_motiva",
                 "nt_work",
                 "not_work",
                 "nt_try",
                 "not_try",
                 "nt_keep",
                 "not_keep",
                 "nt_apply",
                 "not_apply",
                 "refuse_to",
                 "no_effort",
                 "skate_by",
                 "skating_by",
                 "passive",
                 "nt_partic",
                 "not_partic",
                 "just_sit_there",
                 "never_work",
                 "never_partic",
                 "nt_do_anything",
                 "do_nothing",
                 "blank_stare",
                 "they_just_stare",
                 "nt_ask_question",
                 "crickets",
                 "t_even_listen",
                 "sleeping_in_class",
                 "barely_participate",
                 "not_following_discussion",
                 "see_me_as_a_movie",
                 "no_question",
                 "roll_eyes",
                 "nt_react",
                 "not_even_looking",
                 "deads_down",
                 "on_their_phone",
                 "distracted",
                 "playing_games",
                 "wearing_headphones",
                 "listening_to_headphones",
                 "texts",
                 "nt_turn_camera_on",
                 "nt_turn_on_mic",
                 "nt_type_in_chat",
                 "no_one_responds",
                 "muted",
                 "talking_to_myself",
                 "why_does_it_matter",
                 "whatever",
                 "blow_off",
                 "shrug_off",
                 "act_out",
                 "acting_out",
                 "interupt",
                 "student_abruptly_state",
                 "dismissive_remark",
                 "doesnt_matter",
                 "ignore_schedule",
                 "want_preference",
                 "should_accommodate",
                 "demanding",
                 "nt_try_before",
                 "to_try",
                 "expecting_to_be_accommodated",
                 "vacations_during_the_semester",
                 "zero_work_ethic",
                 "no_work_ethic",
                 "motivation_is_dead",
                 "breezed_through_highschool",
                 "concerned_with_points",
                 "resistance_to_knowing",
                 "resist_learning",
                 "cant_be_bother",
                 "teased",
                 "be_made_fun_of",
                 "worried_about_others",
                 "afraid_to_try",
                 "immediate_perfection",
                 "they_shut_down",
                 "cope_with_failure",
                 "not_willing_to_try",
                 "emotionally_safe",
                 "lack_of_effort",
                 "not_wanting_to",
                 "nt_practice",
                 "not_practice",
                 "afraid_to_fail",
                 "fear_of_fail",
                 "fear_of_try",
                 "insecur",
                 "worse_than_last_year",
                 "is_it_just_my_school",
                 "dumbed_down",
                 "many_students_didnt_understand",
                 "not_just_a_few_students",
                 "no_in_between",
                 "lower_half_has_plummeted",
                 "say_they_never_learned",
                 "increasing_proportion_of_students",
                 "never_did_before",
                 "because_our_admin",
                 "zero_consequences",
                 "fail_them",
                 "no_consequences",
                 "failing",
                 "passed_along",
                 "accountable_for_their_failure",
                 "they_know_they_arent",
                 "not_fail",
                 "nt_fail",
                 "lack_of_consequences",
                 "without_consequences",
                 "consumer_model",
                 "pleasing_the_customer",
                 "please_the_customer",
                 "customer_is_always_right",
                 "consequences_are_gone",
                 "push_for_fewer_suspensions",
                 "admin_actively_discourage",
                 "disregard_for_the_teacher",
                 "administration_is_scared",
                 "no_discipline",
                 "public_babysitting",
                 "inmates_run_the_asylum",
                 "accountability_for_admin",
                 "responsibility_but_no_power",
                 "admin_ignores",
                 "admin_wont",
                 "admin_dont",
                 "impossible_to_fail",
                 "entitled",
                 "parent_wants",
                 "nt_hold_their_child_accountable",
                 "helicopter_parent",
                 "reply_from_her_parent",
                 "her_childs_doing",
                 "unfair_that_her_child",
                 "both_parents",
                 "with_her_mother",
                 "with_his_mother",
                 "email_from_the_students",
                 "parents_along_with_them",
                 "parental_intervention",
                 "bring_their_parent",
                 "no_motion",
                 "nonchalant",
                 "nonchalance",
                 "apathy",
                 "apathetic",
                 "nt_stand_out",
                 "nt_want_to_stand_out",
                 "face_in_the_crowd",
                 "no_passion",
                 "too_cool_to_care",
                 "too_tough_to_try",
                 "too_tuff_to_try",
                 "no_personality",
                 "nt_lose_aura",
                 "no_aura",
                 "nt_start_a_conversation",
                 "media_pressures",
                 "nt_care",
                 "no_mistakes",
                 "nt_make_a_mistake",
                 "nt_make_mistakes",
                 "fear_mistakes",
                 "nt_mess_up",
                 "averse_to_taking_risks",
                 "perfect_self_image",
                 "chase_approval",
                 "seek_approval",
                 "chase_praise",
                 "seek_praise",
                 "fear_judgement",
                 "afraid_of_judgement",
                 "nt_want_to_be_judged",
                 "auraless",
                 "never_stops_hustling",
                 "so_passionate",
                 "i_care_deeply",
                 "if_your_team_isnt",
                 "grind_culture",
                 "bosses_to_exploit",
                 "this_isnt_satire",
                 "theyre_locked_in",
                 "hey_are_paid",
                 "my_priorities",
                 "up_by_the_bootstraps",
                 "poser",
                 "of_course",
                 "the_type_of_guy",
                 "trying_to_sell_you",
                 "posting_thirst_traps",
                 "performative_and_cringe",
                 "tenk_month",
                 "niche_a_good_product",
                 "listing_optimization",
                 "partner_with",
                 "affiliates",
                 "influencer",
                 "cash_rides",
                 "cant_be_verified",
                 "safety_reasons",
                 "fraudulent_activity",
                 "honest_drivers",
                 "undesirable_drivers",
                 "scammy",
                 "uber_doesnt_give",
                 "to_scam_you",
                 "lyft_driver",
                 "uber_support",
                 "persons_feedback",
                 "up_the_username",
                 "troll",
                 "profile_shows",
                 "rude",
                 "abusive",
                 "block_them",
                 "bully_other_sellers",
                 "off_the_platform",
                 "the_platform",
                 "report_them",
                 "report_this",
                 "d_cancel",
                 "how_an_item",
                 "signature_confirmation",
                 "cancel_and_block",
                 "red_flag",
                 "trust_your_gut",
                 "the_entitlement",
                 "not_your_fault",
                 "honest_feedback",
                 "leave_a_neg",
                 "just_block",
                 "block_and_report",
                 "threatening_legal",
                 "worst_buyers",
                 "negative_feedback",
                 "move_on",
                 "datamining_app",
                 "laundry_machine",
                 "crazy_expensive",
                 "i_deleted_my_account",
                 "demanding_updates",
                 "smart_t_vs",
                 "healthcare_system",
                 "not_repairable",
                 "your_only_option",
                 "create_a_user_account",
                 "promote_sponsored_result",
                 "ai_crap",
                 "that_garbage",
                 "sponsored_ones",
                 "are_worthless",
                 "forced_to_pay",
                 "youtube_ads",
                 "button_unclickable",
                 "multiple_ads",
                 "dont_bother_watching",
                 "appliances_that_die",
                 "subscribe_to_use",
                 "later_removed",
                 "battery_life",
                 "requirement_to_link",
                 "required_to_link",
                 "must_link_to",
                 "data_will_be_sold",
                 "users_bleed_away",
                 "more_ads_than_content",
                 "minutes_of_ads",
                 "site_got_polluted",
                 "real_names_policy",
                 "prove_it_before",
                 "your_real_name",
                 "legal_name",
                 "cess_pool",
                 "apps_being_required",
                 "app_required",
                 "over_the_air_updates",
                 "subscription_package",
                 "impossible_to_repair",
                 "engagement_farming",
                 "bot_post",
                 "spam",
                 "repost",
                 "cheaper_and_cheaper",
                 "bought_out_by",
                 "investment_firm",
                 "equity_firm",
                 "sucked_dry",
                 "hollowed_out",
                 "lower_quality",
                 "hours_cut",
                 "cutting_corners",
                 "service_breakdown",
                 "service_recovery",
                 "making_money",
                 "showing_my_face",
                 "make_money",
                 "nt_show",
                 "not_show",
                 "ai",
                 "ex")



# Drop the columns using the select() function.
# The 'all_of()' function ensures that only the columns explicitly listed are selected for removal.

df <- df %>%
  select(-all_of(vars_to_drop))

names(df)

fwrite(df, "all_threads_2026_rt.csv")

# see   prep_edu_data.R  file on github for next steps
